src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reimbursed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reimbursed</label>
        <type>Checkbox</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>CAUAE-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DB_ExpenseSelector.cls
public with sharing class DB_ExpenseSelector extends fflib_SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
        		Expense__c.id,
                Expense__c.amount__c,
                Expense__c.client__c,
                Expense__c.createdDate,
                Expense__c.date__c,
                Expense__c.name,
                Expense__c.reimbursed__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Expense__c.sObjectType;
    }

    public List<Expense__c> selectAll() {
        return (List<Expense__c>) Database.query(
                newQueryFactory(true, true, true)
                .toSOQL()
        );
    }
}