src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>CAUAE-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CAUA_ExpenseAuraCtrlIntTest.cls
@isTest
public with sharing class CAUA_ExpenseAuraCtrlIntTest {
	private static final User TEST_RUNNER = TEST_RunAsUserFactory.create();
	
    @isTest public static void testSaveExpense() {
	    // Arrange
	    String description = 'My New Expense';
	    Expense__c expenseTemplate = new Expense__c(description__c = description);
	    Expense__c testExpense = TEST_ExpenseFactory.create(expenseTemplate, TEST_DummyInsertModeEnum.REAL);
	
	    // Act 
	    Expense__c resultExpense;
	    System.runAs(TEST_RUNNER){
	        Test.startTest();
	        {
	            resultExpense = CAUA_ExpenseAuraCtrl.saveExpense(testExpense);
	        }
	        Test.stopTest();
	    }
	
	    // Assert
	    System.assertEquals(testExpense, resultExpense);
	    
	    List<Expense__c> resultList = [SELECT id FROM Expense__c WHERE description__c = :description];
	    System.assertEquals(1, resultList.size());
	    System.assertEquals(description, resultList[0].description__c);
	}
}