src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>CAUAE-{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TEST_ExpenseFactory.cls
public with sharing class TEST_ExpenseFactory extends TEST_SObjectFactory {
	private static Map<String, Object> defaultByKeyMap = new Map<String, Object>{
		'amount__c' => 20.0
	}; 
	
	public static List<Expense__c> createList(Expense__c template, Integer quantity, TEST_DummyInsertModeEnum insertMode){
		MockStrategyInterface strategy = new EquipmentInQuantityStrategy(template, quantity); 
		return (List<Expense__c>) TEST_SObjectFactory.createList(strategy, insertMode); 
	}
	
	public static Expense__c create(Expense__c template, TEST_DummyInsertModeEnum insertMode){
		Integer quantity = 1;
		return createList(template, quantity, insertMode)[0];
	}

	class EquipmentInQuantityStrategy extends SObjectInQuantityStrategy {
		EquipmentInQuantityStrategy(SObject template, Integer quantity) {
			super(template, quantity, 'Expense ', defaultByKeyMap);
		}
	}
}