src/objects/Widget__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Widget</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DB_WidgetSelector.cls
public with sharing class DB_WidgetSelector extends fflib_SObjectSelector {

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
        		Widget__c.id,
                Widget__c.name,
                Widget__c.text__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Widget__c.sObjectType;
    }

    public List<Widget__c> selectAll() {
        return (List<Widget__c>) Database.query(
                newQueryFactory()
                .toSOQL()
        );
    }
}